apiVersion: v1
kind: Namespace
metadata:
  name: locust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telelocust
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telelocust
  template:
    metadata:
      labels:
        app: telelocust
    spec:
      containers:
      - name: telelocust
        image: ghcr.io/wolfkarl/telelocust
        ports:
        - containerPort: 5123
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5123
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: telelocust
  namespace: locust
spec:
  type: NodePort
  selector:
    app: telelocust
  ports:
  - port: 30031
    targetPort: 5123
    nodePort: 30032
